// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrancaBeauty.Infrastructure.EfCore.Context;

namespace PrancaBeauty.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20210923072827_mig9")]
    partial class mig9
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Category.CategoriyAgg.Entities.TblCategoris", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ImageId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("ParentId");

                    b.ToTable("TblCategoris");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Category.CategoriyAgg.Entities.TblCategory_Translates", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LangId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LangId");

                    b.ToTable("TblCategory_Translates");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.FileServer.FileAgg.Entities.TblFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("FileServerId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("SizeOnDisk")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FileServerId");

                    b.HasIndex("UserId");

                    b.ToTable("TblFile");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.FileServer.ServerAgg.Entities.TblFileServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Capacity")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FtpData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HttpDomin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HttpPath")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TblFileServer");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Keywords.KeywordAgg.Entities.tblKeywords", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("tblKeywords");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Keywords.Keywords_Products.Entities.tblKeywords_Products", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KeywordId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Similarity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KeywordId");

                    b.HasIndex("ProductId");

                    b.ToTable("tblKeywords_Products");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductAgg.Entities.tblProducts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorUserId")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descreption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("CategoryId");

                    b.ToTable("tblProducts");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductAskAgg.Entities.tblProductAsk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AskId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirm")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AskId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("tblProductAsk");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductAskLikesAgg.Entities.tblProductAskLikes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductAskId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductAskId");

                    b.HasIndex("UserId");

                    b.ToTable("tblProductAskLikes");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductMediaAgg.Entities.tblProductMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FileId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("tblProductMedia");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductPricesAgg.Entities.tblProductPrices", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("ProductId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("tblProductPrices");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductPropertiesValuesAgg.Entities.tblProductPropertiesValues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductPropertiesId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductPropertiesId");

                    b.ToTable("tblProductPropertiesValues");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductPropertisAgg.Entities.tblProductPropertis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<Guid>("TopicId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("tblProductPropertis");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductPropertisAgg.Entities.tblProductPropertis_Translates", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PropertyId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("LangId");

                    b.HasIndex("PropertyId");

                    b.ToTable("tblProductPropertis_Translates");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductReviewsAgg.Entities.tblProductReviews", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Advantages")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("AuthorUserId")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CountStar")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisAdvantages")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsConfirm")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductSellerId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductSellerId");

                    b.ToTable("tblProductReviews");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductReviewsAttributeAgg.Entities.tblProductReviewsAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TopicId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("tblProductReviewsAttribute");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductReviewsAttributeAgg.Entities.tblProductReviewsAttribute_Translate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductReviewsAttributeId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("LangId");

                    b.HasIndex("ProductReviewsAttributeId");

                    b.ToTable("tblProductReviewsAttribute_Translate");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductReviewsAttributeValuesAgg.Entities.tblProductReviewsAttributeValues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductReviewAttributeId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductReviewId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductReviewAttributeId");

                    b.HasIndex("ProductReviewId");

                    b.ToTable("tblProductReviewsAttributeValues");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductReviewsLikesAgg.Entities.tblProductReviewsLikes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductReviewId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("tblProductReviewsLikes");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductReviewsMediaAgg.Entities.tblProductReviewsMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FileId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductReviewsId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("ProductReviewsId");

                    b.ToTable("tblProductReviewsMedia");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductSellerAgg.Entities.tblProductSellers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Guarantee")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("ProductId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SellerUserId")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SendFrom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerUserId");

                    b.ToTable("tblProductSellers");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductTopicAgg.Entities.tblProductTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FileId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("tblProductTopic");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductTopicAgg.Entities.tblProductTopic_Translates", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductTopicId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LangId");

                    b.HasIndex("ProductTopicId");

                    b.ToTable("tblProductTopic_Translates");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductVariantAgg.Entities.tblProductVariants", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VariantType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("tblProductVariants");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductVariantAgg.Entities.tblProductVariants_Translates", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductVariantId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LangId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("tblProductVariants_Translates");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductVariantItemsAgg.Entities.tblProductVariantItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Percent")
                        .HasColumnType("float");

                    b.Property<Guid>("ProductId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductSellerId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductVariantId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductSellerId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("tblProductVariantItems");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Region.CityAgg.Entities.TblCities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProvinceId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("TblCities");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Region.CityAgg.Entities.TblCities_Translates", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("LangId");

                    b.ToTable("TblCities_Translates");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Region.CountryAgg.Entities.TblCountries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FlagImgId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FlagImgId");

                    b.ToTable("TblCountries");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Region.CountryAgg.Entities.TblCountries_Translates", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("LangId");

                    b.ToTable("TblCountries_Translates");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Region.LanguageAgg.Entities.TblLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("FlagImgId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRtl")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("UseForSiteLanguage")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FlagImgId");

                    b.ToTable("TblLanguage");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Region.ProvinceAgg.Entities.TblProvinces", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("TblProvinces");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Region.ProvinceAgg.Entities.TblProvinces_Translate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProvinceId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LangId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("TblProvinces_Translate");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Setting.SettingAgg.Entities.TblSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInManufacture")
                        .HasColumnType("bit");

                    b.Property<Guid>("LangId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SiteDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SiteEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SitePhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SiteTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LangId");

                    b.ToTable("TblSetting");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Template.TemplateAgg.Entities.TblTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LangId");

                    b.ToTable("TblTemplate");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.User.AccessLevelAgg.Entities.TblAccessLevel_Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessLevelId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevelId");

                    b.HasIndex("RoleId");

                    b.ToTable("TblAccessLevel_Role");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.User.AccessLevelAgg.Entities.TblAccessLevels", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TblAccessLevels");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.User.AddressAgg.Entities.TblAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("CityId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Plaque")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProviceId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unit")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("ProviceId");

                    b.HasIndex("UserId");

                    b.ToTable("TblAddress");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.User.RoleAgg.Entities.TblRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentId")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.HasIndex("ParentId");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.User.SellerAgg.Entities.tblSeller_Translates", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LogoId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SellerId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("LangId");

                    b.HasIndex("LogoId");

                    b.HasIndex("SellerId");

                    b.ToTable("tblSeller_Translates");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.User.SellerAgg.Entities.tblSellers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("tblSellers");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.User.UserAgg.Entities.TblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("AccessLevelId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeller")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LangId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastTrySentSms")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordPhoneNumber")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevelId");

                    b.HasIndex("LangId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.User.RoleAgg.Entities.TblRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.User.UserAgg.Entities.TblUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.User.UserAgg.Entities.TblUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.User.RoleAgg.Entities.TblRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.User.UserAgg.Entities.TblUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.User.UserAgg.Entities.TblUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Category.CategoriyAgg.Entities.TblCategoris", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.FileServer.FileAgg.Entities.TblFile", "tblFiles")
                        .WithMany("tblCategoris")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrancaBeauty.Domain.Category.CategoriyAgg.Entities.TblCategoris", "tblCategory_Parent")
                        .WithMany("tblCategory_Childs")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("tblCategory_Parent");

                    b.Navigation("tblFiles");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Category.CategoriyAgg.Entities.TblCategory_Translates", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Category.CategoriyAgg.Entities.TblCategoris", "tblCategoris")
                        .WithMany("tblCategory_Translates")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Region.LanguageAgg.Entities.TblLanguage", "TblLanguage")
                        .WithMany("tblCategory_Translates")
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tblCategoris");

                    b.Navigation("TblLanguage");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.FileServer.FileAgg.Entities.TblFile", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.FileServer.ServerAgg.Entities.TblFileServer", "TblFileServer")
                        .WithMany("TblFiles")
                        .HasForeignKey("FileServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.User.UserAgg.Entities.TblUser", "TblUser")
                        .WithMany("TblFiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TblFileServer");

                    b.Navigation("TblUser");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Keywords.Keywords_Products.Entities.tblKeywords_Products", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Keywords.KeywordAgg.Entities.tblKeywords", "tblKeywords")
                        .WithMany("tblKeywords_Products")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Product.ProductAgg.Entities.tblProducts", "tblProducts")
                        .WithMany("tblKeywords_Products")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblKeywords");

                    b.Navigation("tblProducts");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductAgg.Entities.tblProducts", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.User.UserAgg.Entities.TblUser", "tblAuthorUser")
                        .WithMany("tblProducts")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Category.CategoriyAgg.Entities.TblCategoris", "tblCategory")
                        .WithMany("tblProducts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tblAuthorUser");

                    b.Navigation("tblCategory");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductAskAgg.Entities.tblProductAsk", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Product.ProductAskAgg.Entities.tblProductAsk", "tblProductAsk_Parent")
                        .WithMany("tblProductAsk_Childs")
                        .HasForeignKey("AskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrancaBeauty.Domain.Product.ProductAgg.Entities.tblProducts", "tblProducts")
                        .WithMany("tblProductAsk")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.User.UserAgg.Entities.TblUser", "tblUsers")
                        .WithMany("tblProductAsk")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tblProductAsk_Parent");

                    b.Navigation("tblProducts");

                    b.Navigation("tblUsers");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductAskLikesAgg.Entities.tblProductAskLikes", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Product.ProductAskAgg.Entities.tblProductAsk", "tblProductAsk")
                        .WithMany("tblProductAskLikes")
                        .HasForeignKey("ProductAskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.User.UserAgg.Entities.TblUser", "tblUsers")
                        .WithMany("tblProductAskLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tblProductAsk");

                    b.Navigation("tblUsers");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductMediaAgg.Entities.tblProductMedia", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.FileServer.FileAgg.Entities.TblFile", "tblFiles")
                        .WithOne("tblProductMedia")
                        .HasForeignKey("PrancaBeauty.Domain.Product.ProductMediaAgg.Entities.tblProductMedia", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Product.ProductAgg.Entities.tblProducts", "tblProducts")
                        .WithMany("tblProductMedia")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblFiles");

                    b.Navigation("tblProducts");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductPricesAgg.Entities.tblProductPrices", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Product.ProductAgg.Entities.tblProducts", "tblProducts")
                        .WithMany("tblProductPrices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.User.UserAgg.Entities.TblUser", "tblUsers")
                        .WithMany("tblProductPrices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tblProducts");

                    b.Navigation("tblUsers");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductPropertiesValuesAgg.Entities.tblProductPropertiesValues", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Product.ProductAgg.Entities.tblProducts", "tblProducts")
                        .WithMany("tblProductPropertiesValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Product.ProductPropertisAgg.Entities.tblProductPropertis", "tblProductPropertis")
                        .WithMany("tblProductPropertiesValues")
                        .HasForeignKey("ProductPropertiesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tblProductPropertis");

                    b.Navigation("tblProducts");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductPropertisAgg.Entities.tblProductPropertis", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Product.ProductTopicAgg.Entities.tblProductTopic", "tblProductTopic")
                        .WithMany("tblProductPropertis")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tblProductTopic");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductPropertisAgg.Entities.tblProductPropertis_Translates", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Region.LanguageAgg.Entities.TblLanguage", "tblLanguages")
                        .WithMany("tblProductPropertis_Translates")
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Product.ProductPropertisAgg.Entities.tblProductPropertis", "tblProductPropertis")
                        .WithMany("tblProductPropertis_Translates")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblLanguages");

                    b.Navigation("tblProductPropertis");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductReviewsAgg.Entities.tblProductReviews", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.User.UserAgg.Entities.TblUser", "tblUsers")
                        .WithMany("tblProductReviews")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Product.ProductAgg.Entities.tblProducts", "tblProducts")
                        .WithMany("tblProductReviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Product.ProductSellerAgg.Entities.tblProductSellers", "tblProductSellers")
                        .WithMany("tblProductReviews")
                        .HasForeignKey("ProductSellerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("tblProducts");

                    b.Navigation("tblProductSellers");

                    b.Navigation("tblUsers");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductReviewsAttributeAgg.Entities.tblProductReviewsAttribute", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Product.ProductTopicAgg.Entities.tblProductTopic", "tblProductTopic")
                        .WithMany("tblProductReviewsAttribute")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tblProductTopic");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductReviewsAttributeAgg.Entities.tblProductReviewsAttribute_Translate", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Region.LanguageAgg.Entities.TblLanguage", "tblLanguages")
                        .WithMany("tblProductReviewsAttribute_Translate")
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Product.ProductReviewsAttributeAgg.Entities.tblProductReviewsAttribute", "tblProductReviewsAttribute")
                        .WithMany("tblProductReviewsAttribute_Translate")
                        .HasForeignKey("ProductReviewsAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblLanguages");

                    b.Navigation("tblProductReviewsAttribute");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductReviewsAttributeValuesAgg.Entities.tblProductReviewsAttributeValues", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Product.ProductReviewsAttributeAgg.Entities.tblProductReviewsAttribute", "tblProductReviewsAttribute")
                        .WithMany("tblProductReviewsAttributeValues")
                        .HasForeignKey("ProductReviewAttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Product.ProductReviewsAgg.Entities.tblProductReviews", "tblProductReviews")
                        .WithMany("tblProductReviewsAttributeValues")
                        .HasForeignKey("ProductReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblProductReviews");

                    b.Navigation("tblProductReviewsAttribute");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductReviewsLikesAgg.Entities.tblProductReviewsLikes", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Product.ProductReviewsAgg.Entities.tblProductReviews", "tblProductReviews")
                        .WithMany("tblProductReviewsLikes")
                        .HasForeignKey("ProductReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.User.UserAgg.Entities.TblUser", "tblUsers")
                        .WithMany("tblProductReviewsLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tblProductReviews");

                    b.Navigation("tblUsers");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductReviewsMediaAgg.Entities.tblProductReviewsMedia", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.FileServer.FileAgg.Entities.TblFile", "tblFiles")
                        .WithOne("tblProductReviewsMedia")
                        .HasForeignKey("PrancaBeauty.Domain.Product.ProductReviewsMediaAgg.Entities.tblProductReviewsMedia", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Product.ProductReviewsAgg.Entities.tblProductReviews", "tblProductReviews")
                        .WithMany("tblProductReviewsMedia")
                        .HasForeignKey("ProductReviewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblFiles");

                    b.Navigation("tblProductReviews");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductSellerAgg.Entities.tblProductSellers", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Product.ProductAgg.Entities.tblProducts", "tblProducts")
                        .WithMany("tblProductSellers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.User.UserAgg.Entities.TblUser", "tblUsers")
                        .WithMany("tblProductSellers")
                        .HasForeignKey("SellerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblProducts");

                    b.Navigation("tblUsers");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductTopicAgg.Entities.tblProductTopic", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.FileServer.FileAgg.Entities.TblFile", "tblFiles")
                        .WithMany("tblProductTopic")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tblFiles");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductTopicAgg.Entities.tblProductTopic_Translates", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Region.LanguageAgg.Entities.TblLanguage", "tblLanguages")
                        .WithMany("tblProductTopic_Translates")
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Product.ProductTopicAgg.Entities.tblProductTopic", "tblProductTopic")
                        .WithMany("tblProductTopic_Translates")
                        .HasForeignKey("ProductTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblLanguages");

                    b.Navigation("tblProductTopic");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductVariantAgg.Entities.tblProductVariants_Translates", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Region.LanguageAgg.Entities.TblLanguage", "tblLanguages")
                        .WithMany("tblProductVariants_Translates")
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Product.ProductVariantAgg.Entities.tblProductVariants", "tblProductVariants")
                        .WithMany("tblProductVariants_Translates")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblLanguages");

                    b.Navigation("tblProductVariants");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductVariantItemsAgg.Entities.tblProductVariantItems", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Product.ProductAgg.Entities.tblProducts", "tblProducts")
                        .WithMany("tblProductVariantItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Product.ProductSellerAgg.Entities.tblProductSellers", "tblProductSellers")
                        .WithMany("tblProductVariantItems")
                        .HasForeignKey("ProductSellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Product.ProductVariantAgg.Entities.tblProductVariants", "tblProductVariants")
                        .WithMany("tblProductVariantItems")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tblProducts");

                    b.Navigation("tblProductSellers");

                    b.Navigation("tblProductVariants");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Region.CityAgg.Entities.TblCities", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Region.ProvinceAgg.Entities.TblProvinces", "TblProvince")
                        .WithMany("tblCities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TblProvince");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Region.CityAgg.Entities.TblCities_Translates", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Region.CityAgg.Entities.TblCities", "tblCity")
                        .WithMany("TblCities_Translates")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Region.LanguageAgg.Entities.TblLanguage", "tblLanguage")
                        .WithMany("tblCities_Translates")
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tblCity");

                    b.Navigation("tblLanguage");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Region.CountryAgg.Entities.TblCountries", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.FileServer.FileAgg.Entities.TblFile", "tblFiles")
                        .WithMany("TblCountries")
                        .HasForeignKey("FlagImgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tblFiles");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Region.CountryAgg.Entities.TblCountries_Translates", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Region.CountryAgg.Entities.TblCountries", "TblCountrie")
                        .WithMany("tblCountries_Translates")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Region.LanguageAgg.Entities.TblLanguage", "TblLanguage")
                        .WithMany("tblCountries_Translates")
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TblCountrie");

                    b.Navigation("TblLanguage");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Region.LanguageAgg.Entities.TblLanguage", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.FileServer.FileAgg.Entities.TblFile", "TblFile")
                        .WithMany("TblLanguages")
                        .HasForeignKey("FlagImgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TblFile");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Region.ProvinceAgg.Entities.TblProvinces", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Region.CountryAgg.Entities.TblCountries", "tblCountry")
                        .WithMany("TblProvinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tblCountry");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Region.ProvinceAgg.Entities.TblProvinces_Translate", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Region.LanguageAgg.Entities.TblLanguage", "TblLanguage")
                        .WithMany("tblProvinces_Translate")
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Region.ProvinceAgg.Entities.TblProvinces", "TblProvinces")
                        .WithMany("tblProvinces_Translate")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TblLanguage");

                    b.Navigation("TblProvinces");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Setting.SettingAgg.Entities.TblSetting", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Region.LanguageAgg.Entities.TblLanguage", "TblLanguage")
                        .WithMany("TblSettings")
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TblLanguage");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Template.TemplateAgg.Entities.TblTemplate", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Region.LanguageAgg.Entities.TblLanguage", "Language")
                        .WithMany("TblTemplates")
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.User.AccessLevelAgg.Entities.TblAccessLevel_Role", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.User.AccessLevelAgg.Entities.TblAccessLevels", "TblAccessLevels")
                        .WithMany("TblAccessLevel_Roles")
                        .HasForeignKey("AccessLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.User.RoleAgg.Entities.TblRole", "TblRole")
                        .WithMany("TblAccessLevel_Roles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TblAccessLevels");

                    b.Navigation("TblRole");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.User.AddressAgg.Entities.TblAddress", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Region.CityAgg.Entities.TblCities", "tblCities")
                        .WithMany("tblAddress")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Region.CountryAgg.Entities.TblCountries", "TblCountries")
                        .WithMany("tblAddress")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Region.ProvinceAgg.Entities.TblProvinces", "tblProvinces")
                        .WithMany("tblAddress")
                        .HasForeignKey("ProviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.User.UserAgg.Entities.TblUser", "TblUser")
                        .WithMany("TblAddress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("tblCities");

                    b.Navigation("TblCountries");

                    b.Navigation("tblProvinces");

                    b.Navigation("TblUser");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.User.RoleAgg.Entities.TblRole", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.User.RoleAgg.Entities.TblRole", "tblRoles_Parent")
                        .WithMany("tblRoles_Childs")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("tblRoles_Parent");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.User.SellerAgg.Entities.tblSeller_Translates", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.Region.LanguageAgg.Entities.TblLanguage", "tblLanguages")
                        .WithMany("tblSeller_Translates")
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.FileServer.FileAgg.Entities.TblFile", "tblFiles")
                        .WithMany("tblSeller_Translates")
                        .HasForeignKey("LogoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrancaBeauty.Domain.User.SellerAgg.Entities.tblSellers", "tblSellers")
                        .WithMany("tblSeller_Translates")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblFiles");

                    b.Navigation("tblLanguages");

                    b.Navigation("tblSellers");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.User.SellerAgg.Entities.tblSellers", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.User.UserAgg.Entities.TblUser", "tblUsers")
                        .WithOne("tblSellers")
                        .HasForeignKey("PrancaBeauty.Domain.User.SellerAgg.Entities.tblSellers", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblUsers");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.User.UserAgg.Entities.TblUser", b =>
                {
                    b.HasOne("PrancaBeauty.Domain.User.AccessLevelAgg.Entities.TblAccessLevels", "TblAccessLevels")
                        .WithMany("TblUsers")
                        .HasForeignKey("AccessLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrancaBeauty.Domain.Region.LanguageAgg.Entities.TblLanguage", "TblLanguage")
                        .WithMany("tblUsers")
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TblAccessLevels");

                    b.Navigation("TblLanguage");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Category.CategoriyAgg.Entities.TblCategoris", b =>
                {
                    b.Navigation("tblCategory_Childs");

                    b.Navigation("tblCategory_Translates");

                    b.Navigation("tblProducts");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.FileServer.FileAgg.Entities.TblFile", b =>
                {
                    b.Navigation("tblCategoris");

                    b.Navigation("TblCountries");

                    b.Navigation("TblLanguages");

                    b.Navigation("tblProductMedia");

                    b.Navigation("tblProductReviewsMedia");

                    b.Navigation("tblProductTopic");

                    b.Navigation("tblSeller_Translates");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.FileServer.ServerAgg.Entities.TblFileServer", b =>
                {
                    b.Navigation("TblFiles");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Keywords.KeywordAgg.Entities.tblKeywords", b =>
                {
                    b.Navigation("tblKeywords_Products");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductAgg.Entities.tblProducts", b =>
                {
                    b.Navigation("tblKeywords_Products");

                    b.Navigation("tblProductAsk");

                    b.Navigation("tblProductMedia");

                    b.Navigation("tblProductPrices");

                    b.Navigation("tblProductPropertiesValues");

                    b.Navigation("tblProductReviews");

                    b.Navigation("tblProductSellers");

                    b.Navigation("tblProductVariantItems");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductAskAgg.Entities.tblProductAsk", b =>
                {
                    b.Navigation("tblProductAsk_Childs");

                    b.Navigation("tblProductAskLikes");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductPropertisAgg.Entities.tblProductPropertis", b =>
                {
                    b.Navigation("tblProductPropertiesValues");

                    b.Navigation("tblProductPropertis_Translates");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductReviewsAgg.Entities.tblProductReviews", b =>
                {
                    b.Navigation("tblProductReviewsAttributeValues");

                    b.Navigation("tblProductReviewsLikes");

                    b.Navigation("tblProductReviewsMedia");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductReviewsAttributeAgg.Entities.tblProductReviewsAttribute", b =>
                {
                    b.Navigation("tblProductReviewsAttribute_Translate");

                    b.Navigation("tblProductReviewsAttributeValues");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductSellerAgg.Entities.tblProductSellers", b =>
                {
                    b.Navigation("tblProductReviews");

                    b.Navigation("tblProductVariantItems");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductTopicAgg.Entities.tblProductTopic", b =>
                {
                    b.Navigation("tblProductPropertis");

                    b.Navigation("tblProductReviewsAttribute");

                    b.Navigation("tblProductTopic_Translates");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Product.ProductVariantAgg.Entities.tblProductVariants", b =>
                {
                    b.Navigation("tblProductVariantItems");

                    b.Navigation("tblProductVariants_Translates");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Region.CityAgg.Entities.TblCities", b =>
                {
                    b.Navigation("tblAddress");

                    b.Navigation("TblCities_Translates");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Region.CountryAgg.Entities.TblCountries", b =>
                {
                    b.Navigation("tblAddress");

                    b.Navigation("tblCountries_Translates");

                    b.Navigation("TblProvinces");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Region.LanguageAgg.Entities.TblLanguage", b =>
                {
                    b.Navigation("tblCategory_Translates");

                    b.Navigation("tblCities_Translates");

                    b.Navigation("tblCountries_Translates");

                    b.Navigation("tblProductPropertis_Translates");

                    b.Navigation("tblProductReviewsAttribute_Translate");

                    b.Navigation("tblProductTopic_Translates");

                    b.Navigation("tblProductVariants_Translates");

                    b.Navigation("tblProvinces_Translate");

                    b.Navigation("tblSeller_Translates");

                    b.Navigation("TblSettings");

                    b.Navigation("TblTemplates");

                    b.Navigation("tblUsers");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.Region.ProvinceAgg.Entities.TblProvinces", b =>
                {
                    b.Navigation("tblAddress");

                    b.Navigation("tblCities");

                    b.Navigation("tblProvinces_Translate");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.User.AccessLevelAgg.Entities.TblAccessLevels", b =>
                {
                    b.Navigation("TblAccessLevel_Roles");

                    b.Navigation("TblUsers");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.User.RoleAgg.Entities.TblRole", b =>
                {
                    b.Navigation("TblAccessLevel_Roles");

                    b.Navigation("tblRoles_Childs");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.User.SellerAgg.Entities.tblSellers", b =>
                {
                    b.Navigation("tblSeller_Translates");
                });

            modelBuilder.Entity("PrancaBeauty.Domain.User.UserAgg.Entities.TblUser", b =>
                {
                    b.Navigation("TblAddress");

                    b.Navigation("TblFiles");

                    b.Navigation("tblProductAsk");

                    b.Navigation("tblProductAskLikes");

                    b.Navigation("tblProductPrices");

                    b.Navigation("tblProductReviews");

                    b.Navigation("tblProductReviewsLikes");

                    b.Navigation("tblProducts");

                    b.Navigation("tblProductSellers");

                    b.Navigation("tblSellers");
                });
#pragma warning restore 612, 618
        }
    }
}
